image: ubuntu:17.10

variables:
  DOCKER_DRIVER: overlay

stages:
  - test
  - package

before_script:
  - apt update -qq
  - DEBIAN_FRONTEND=noninteractive apt install -y curl wget build-essential git-core zip cmake automake libtool libxcb-shm0-dev libxrandr-dev libxi-dev libgsl0-dev libatlas3-base libgphoto2-dev libxinerama-dev libxcursor-dev python3-dev portaudio19-dev yasm libgl1-mesa-dev libopencv-dev python
  - git submodule update --init
  - ./make_deps.sh
  - rm -rf build && mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ..

#
# Tests
#
test:17.10:
  stage: test
  image: ubuntu:17.10
  script: 
    - make -j$(nproc)
    - make test

test:18.04:
  stage: test
  image: ubuntu:18.04
  script: 
    - make -j$(nproc)
    - make test

test:archlinux:
  stage: test
  image: base/archlinux
  only:
    - archlinux
  before_script:
    - pacman -Syyu --noconfirm
    - pacman -Sy --noconfirm git cmake make gcc yasm pkgconfig libxi libxinerama libxrandr libxcursor mesa glm gsl libgphoto2 opencv python3 portaudio zip zlib
    - git submodule update --init
    - ./make_deps.sh
    - rm -rf build && mkdir build && cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
  script:
    - make -j$(nproc)
    - make test

#
# Package
#
package:
  stage: package
  script:
    - make -j$(nproc)
    - make package
    - mv *.deb ../
    - mv addons/blender/*.tar.bz2 ../
  only:
    - tags
  artifacts:
    name: "splash_${CI_BUILD_REF_NAME}"
    paths:
    - "*.deb"
    - "*.tar.bz2"

#
# Static analysis
#
static_analysis:
  stage: test
  script:
    - wget https://scan.coverity.com/download/linux64 --post-data "token=zkRfEWYxyAeJDlYYg9Hkkg&project=paperManu%2Fsplash" -O coverity_tool.tgz
    - tar xvzf coverity_tool.tgz
    - $(ls | grep cov-analysis)/bin/cov-build --dir cov-int make -j$(nproc)
    - tar caf splash-cov.bz2 cov-int
    - curl --form token=zkRfEWYxyAeJDlYYg9Hkkg --form email=emmanueldurand@gmail.com --form file=@splash-cov.bz2 --form description="Splash" https://scan.coverity.com/builds?project=paperManu%2Fsplash
    - apt install -y libpcre3-dev
    - make static_analysis
    - mv tests/static_analysis_result.txt ../
  only:
    - static_analysis
  artifacts:
    name: "splash_static_analysis_${CI_BUILD_REF_NAME}"
    paths:
    - "static_analysis_result.txt"

