image: ubuntu:xenial

variables:
  DOCKER_DRIVER: overlay

before_script: 
  - apt update -qq
  - apt install -y curl wget build-essential git-core zip cmake automake libtool libxrandr-dev libxi-dev libgsl0-dev libatlas3-base libgphoto2-dev libxinerama-dev libxcursor-dev python3-dev portaudio19-dev yasm libgl1-mesa-dev python
  - git submodule update --init
  - ./make_deps.sh
  - rm -rf build && mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ..

stages:
  - test:xenial
  - test:artful
  - package
  - static_analysis

test:xenial:
  image: ubuntu:xenial
  stage: test:xenial
  script: 
    - make -j$(nproc)
    - make test

test:artful:
  image: ubuntu:artful
  stage: test:artful
  script: 
    - make -j$(nproc)
    - make test

package:
  stage: package
  script:
    - make -j$(nproc)
    - make package
    - mv *.deb ../
    - mv addons/blender/*.tar.bz2 ../
  only:
    - tags
  artifacts:
    name: "splash_${CI_BUILD_REF_NAME}"
    paths:
    - "*.deb"
    - "*.tar.bz2"

static_analysis:
  stage: static_analysis
  script:
    - wget https://scan.coverity.com/download/linux64 --post-data "token=zkRfEWYxyAeJDlYYg9Hkkg&project=paperManu%2Fsplash" -O coverity_tool.tgz
    - tar xvzf coverity_tool.tgz
    - $(ls | grep cov-analysis)/bin/cov-build --dir cov-int make -j$(nproc)
    - tar caf splash-cov.bz2 cov-int
    - curl --form token=zkRfEWYxyAeJDlYYg9Hkkg --form email=emmanueldurand@gmail.com --form file=@splash-cov.bz2 --form description="Splash" https://scan.coverity.com/builds?project=paperManu%2Fsplash
    - apt install -y libpcre3-dev
    - make static_analysis
    - mv tests/static_analysis_result.txt ../
  only:
    - static_analysis
  artifacts:
    name: "splash_static_analysis_${CI_BUILD_REF_NAME}"
    paths:
    - "static_analysis_result.txt"

