variables:
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - coverage
  - deploy

cache:
  paths:
    - ccache/

#
# ╺┳╸┏━╸┏━┓╺┳╸┏━┓
#  ┃ ┣╸ ┗━┓ ┃ ┗━┓
#  ╹ ┗━╸┗━┛ ╹ ┗━┛
#

before_script:
  - apt update -qq
  - DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends ca-certificates
    ccache wget curl build-essential git-core libjsoncpp-dev zip cmake automake libtool
    libxcb-shm0-dev libxrandr-dev libxi-dev libgsl0-dev libatlas3-base libgphoto2-dev
    libxinerama-dev libxcursor-dev python3-dev portaudio19-dev yasm libgl1-mesa-dev
    libopencv-dev libx264-dev libx265-dev

  # CCache stuff
  - mkdir -p ccache
  - export CCACHE_BASEDIR=${PWD}
  - export CCACHE_DIR=${PWD}/ccache
  - export PATH="/usr/lib/ccache:${PATH}"

test:20.04:gcc-bundled-libs:
  stage: test
  image: ubuntu:20.04
  script: 
    # Install Metalab packages
    - apt install -y --no-install-recommends software-properties-common
    - add-apt-repository -y ppa:sat-metalab/metalab
    - DEBIAN_FRONTEND=noninteractive apt install -y libshmdata-dev

    # Prepare bundled dependencies
    - ./make_deps.sh

    # Test using bundled libs
    - rm -rf build && mkdir build
    - cmake -B build -DBUILD_GENERIC_ARCH=ON -DCMAKE_INSTALL_PREFIX=/usr
    - make -sC build -j$(nproc)
    - make test -sC build
    - ./build/src/splash --child --prefix unittest &
    - ./build/src/splash --doNotSpawn --prefix unittest ./data/share/splash/splash.json
  except:
    - /^debian.*$/

test:20.04:clang-bundled-libs:
  stage: test
  image: ubuntu:20.04
  script: 
    # Install Metalab packages
    - apt install -y --no-install-recommends software-properties-common
    - add-apt-repository -y ppa:sat-metalab/metalab
    - DEBIAN_FRONTEND=noninteractive apt install -y libshmdata-dev

    # Prepare bundled dependencies
    - ./make_deps.sh

    # Test using Clang
    - DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends clang
    - rm -rf build && mkdir build
    - CC=clang CXX=clang++ cmake -B build -DBUILD_GENERIC_ARCH=ON -DCMAKE_INSTALL_PREFIX=/usr
    - make -sC build -j$(nproc)
    - make test -sC build
    - ./build/src/splash --child --prefix unittest &
    - ./build/src/splash --doNotSpawn --prefix unittest ./data/share/splash/splash.json
  except:
    - /^debian.*$/

test:20.04:gcc-system-libs:
  stage: test
  image: ubuntu:20.04
  script: 
    # Install Metalab packages
    - apt install -y --no-install-recommends software-properties-common
    - add-apt-repository -y ppa:sat-metalab/metalab
    - DEBIAN_FRONTEND=noninteractive apt install -y libshmdata-dev

    # Test using system libs
    - DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends libglfw3-dev libglm-dev
      libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libsnappy-dev libzmq3-dev libzmqpp-dev
    - rm -rf build && mkdir build
    - cmake -B build -DBUILD_GENERIC_ARCH=ON -DCMAKE_INSTALL_PREFIX=/usr -DUSE_SYSTEM_LIBS=ON
    - make -sC build -j$(nproc)
    - make test -sC build
    - ./build/src/splash --child --prefix unittest &
    - ./build/src/splash --doNotSpawn --prefix unittest ./data/share/splash/splash.json
  except:
    - website
    - /^debian.*$/

test:22.04:gcc-bundled-libs:
  stage: test
  image: ubuntu:22.04
  script: 
    # Prepare bundled dependencies
    - ./make_deps.sh

    # Test using bundled libs
    - rm -rf build && mkdir build
    - cmake -B build -DBUILD_GENERIC_ARCH=ON -DCMAKE_INSTALL_PREFIX=/usr
    - make -sC build -j$(nproc)
    - make test -sC build
    - ./build/src/splash --child --prefix unittest &
    - ./build/src/splash --doNotSpawn --prefix unittest ./data/share/splash/splash.json
  except:
    - /^debian.*$/

test:22.04:clang-bundled-libs:
  stage: test
  image: ubuntu:22.04
  script: 
    # Prepare bundled dependencies
    - ./make_deps.sh

    # Test using Clang
    - DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends clang
    - rm -rf build && mkdir build
    - CC=clang CXX=clang++ cmake -B build -DBUILD_GENERIC_ARCH=ON -DCMAKE_INSTALL_PREFIX=/usr
    - make -sC build -j$(nproc)
    - make test -sC build
    - ./build/src/splash --child --prefix unittest &
    - ./build/src/splash --doNotSpawn --prefix unittest ./data/share/splash/splash.json
  except:
    - /^debian.*$/

test:22.04:gcc-system-libs:
  stage: test
  image: ubuntu:22.04
  script: 
    # Test using system libs
    - DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends libglfw3-dev libglm-dev
      libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libsnappy-dev libzmq3-dev
    - rm -rf build && mkdir build
    - cmake -B build -DBUILD_GENERIC_ARCH=ON -DCMAKE_INSTALL_PREFIX=/usr -DUSE_SYSTEM_LIBS=ON
    - make -sC build -j$(nproc)
    - make test -sC build
    - ./build/src/splash --child --prefix unittest &
    - ./build/src/splash --doNotSpawn --prefix unittest ./data/share/splash/splash.json
  except:
    - website
    - /^debian.*$/

test:archlinux:
  stage: test
  image: archlinux:latest
  before_script:
    - pacman -Syyu --noconfirm
    - pacman -Sy --noconfirm git cmake make gcc yasm ccache pkgconfig libxi libxinerama libxrandr
      libxcursor jsoncpp mesa gsl libgphoto2 python3 portaudio zip zlib x264 x265 opencv qt5-base vtk
      hdf5 glew fmt openmpi
    - mkdir -p ccache
    - export CCACHE_BASEDIR=${PWD}
    - export CCACHE_DIR=${PWD}/ccache
    - export PATH="/usr/lib/ccache:${PATH}"
    - ./make_deps.sh
    - rm -rf build && mkdir build && cd build
  script:
    - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
    - make -j$(nproc)
    - make test
  except:
    - /^debian.*$/

#
# Test coverage
#
coverage:
  stage: coverage
  image: ubuntu:20.04
  script: 
    # Install Metalab packages
    - apt install -y --no-install-recommends software-properties-common
    - add-apt-repository -y ppa:sat-metalab/metalab
    - DEBIAN_FRONTEND=noninteractive apt install -y libshmdata-dev

    # Install coverage tools
    - DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends lcov zip
    - ./make_deps.sh
    - rm -rf build && mkdir build && cd build
    - cmake -DTEST_COVERAGE=ON -DBUILD_GENERIC_ARCH=ON -DCMAKE_INSTALL_PREFIX=/usr ..
    - make -j$(nproc)
    - make check_coverage
    - zip -r coverage.zip coverage
    - mv coverage.zip ../
  artifacts:
    name: "splash_coverage_${CI_BUILD_REF_NAME}"
    paths:
    - "coverage.zip"
  except:
    - website

#
# ┏━┓┏━┓┏━╸╻┏ ┏━┓┏━╸┏━╸
# ┣━┛┣━┫┃  ┣┻┓┣━┫┃╺┓┣╸ 
# ╹  ╹ ╹┗━╸╹ ╹╹ ╹┗━┛┗━╸
#
package:debian:
  stage: deploy
  image: ubuntu:20.04
  script:
    # Install Metalab packages
    - apt install -y --no-install-recommends software-properties-common
    - add-apt-repository -y ppa:sat-metalab/metalab
    - DEBIAN_FRONTEND=noninteractive apt install -y libshmdata-dev

    # Build package
    - ./make_deps.sh
    - rm -rf build && mkdir build && cd build
    - cmake -DBUILD_GENERIC_ARCH=ON -DWITH_LTO=ON -DCMAKE_INSTALL_PREFIX=/usr ..
    - make -j$(nproc)
    - make package
    - mv *.deb ../
    - mv addons/blender/*.tar.bz2 ../
  only:
    - tags
  artifacts:
    name: "splash_${CI_BUILD_REF_NAME}"
    paths:
      - "*.deb"
      - "*.tar.bz2"

include:
  - remote: 'https://gitlab.com/sat-metalab/distributions/mpa-bionic-arm64-jetson/-/raw/main/.gitlab-ci-package.yml'
  - remote: 'https://gitlab.com/sat-metalab/distributions/mpa-focal-amd64-nvidia/-/raw/main/.gitlab-ci-package.yml'

#
# ┏━┓╺┳╸┏━┓╺┳╸╻┏━╸   ┏━┓┏┓╻┏━┓╻  ╻ ╻┏━┓╻┏━┓
# ┗━┓ ┃ ┣━┫ ┃ ┃┃     ┣━┫┃┗┫┣━┫┃  ┗┳┛┗━┓┃┗━┓
# ┗━┛ ╹ ╹ ╹ ╹ ╹┗━╸   ╹ ╹╹ ╹╹ ╹┗━╸ ╹ ┗━┛╹┗━┛
#
static_analysis:
  stage: test
  image: ubuntu:20.04
  script:
    - git submodule update --init
    - ./make_deps.sh
    - rm -rf build && mkdir build && cd build
    - cmake -DBUILD_GENERIC_ARCH=ON -DCMAKE_INSTALL_PREFIX=/usr ..
    - wget https://scan.coverity.com/download/linux64 --post-data "token=zkRfEWYxyAeJDlYYg9Hkkg&project=paperManu%2Fsplash"
      -O coverity_tool.tgz
    - tar xvzf coverity_tool.tgz
    - $(ls | grep cov-analysis)/bin/cov-build --dir cov-int make -j$(nproc)
    - tar caf splash-cov.bz2 cov-int
    - curl --form token=zkRfEWYxyAeJDlYYg9Hkkg --form email=emmanueldurand@gmail.com --form file=@splash-cov.bz2
      --form description="Splash" https://scan.coverity.com/builds?project=paperManu%2Fsplash
    - DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends libpcre3-dev cppcheck
    - make static_analysis
    - mv tests/static_analysis_result.txt ../
  only:
    - static_analysis
  artifacts:
    name: "splash_static_analysis_${CI_BUILD_REF_NAME}"
    paths:
    - "static_analysis_result.txt"

#
# ┏━╸╻╺┳╸╻  ┏━┓┏┓    ┏━┓┏━┓┏━╸┏━╸┏━┓
# ┃╺┓┃ ┃ ┃  ┣━┫┣┻┓   ┣━┛┣━┫┃╺┓┣╸ ┗━┓
# ┗━┛╹ ╹ ┗━╸╹ ╹┗━┛   ╹  ╹ ╹┗━┛┗━╸┗━┛
#
pages:
  stage: deploy
  image: ubuntu:20.04
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    # Build the dependencies.
    # Needed for CMake to succeed and build API doc
    - ./make_deps.sh

    # Build the website
    - DEBIAN_FRONTEND=noninteractive apt install -y python3-pip doxygen graphviz
    - git clone https://gitlab.com/sat-metalab/documentations/splash splash-doc
    - pushd splash-doc
    - git pull origin master # Make sure to be up-to-date
    - pip install -U sphinx
    - pip install -r requirements.txt
    - make htmlgitlab
    - popd

    # Build the API doc
    - mkdir -p build && pushd build
    - cmake .. && make doc && cp -r docs/html ../splash-doc/public/doxygen
    - popd

    # Gather documentation togeter
    - mv splash-doc/public public

    # Build the packages
    - pushd build
    - cmake -DBUILD_GENERIC_ARCH=ON -DWITH_LTO=ON -DCMAKE_INSTALL_PREFIX=/usr ..
    - make -j$(nproc)
    - make package
    - mv *.deb ../public/splash.deb
    - mv addons/blender/*.tar.bz2 ../public/blender_splash_addon.tar.bz2
    - popd
  artifacts:
    paths:
      - public
  only:
    - website
